# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/ben/Bureau/Coding/C C++/SystemAirport"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/ben/Bureau/Coding/C C++/SystemAirport"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/ben/Bureau/Coding/C C++/SystemAirport/CMakeFiles" "/home/ben/Bureau/Coding/C C++/SystemAirport/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/ben/Bureau/Coding/C C++/SystemAirport/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SystemAirport

# Build rule for target.
SystemAirport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SystemAirport
.PHONY : SystemAirport

# fast build rule for target.
SystemAirport/fast:
	$(MAKE) -f CMakeFiles/SystemAirport.dir/build.make CMakeFiles/SystemAirport.dir/build
.PHONY : SystemAirport/fast

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/SystemAirport.dir/build.make CMakeFiles/SystemAirport.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/SystemAirport.dir/build.make CMakeFiles/SystemAirport.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/SystemAirport.dir/build.make CMakeFiles/SystemAirport.dir/src/main.c.s
.PHONY : src/main.c.s

src/plane.o: src/plane.c.o

.PHONY : src/plane.o

# target to build an object file
src/plane.c.o:
	$(MAKE) -f CMakeFiles/SystemAirport.dir/build.make CMakeFiles/SystemAirport.dir/src/plane.c.o
.PHONY : src/plane.c.o

src/plane.i: src/plane.c.i

.PHONY : src/plane.i

# target to preprocess a source file
src/plane.c.i:
	$(MAKE) -f CMakeFiles/SystemAirport.dir/build.make CMakeFiles/SystemAirport.dir/src/plane.c.i
.PHONY : src/plane.c.i

src/plane.s: src/plane.c.s

.PHONY : src/plane.s

# target to generate assembly for a file
src/plane.c.s:
	$(MAKE) -f CMakeFiles/SystemAirport.dir/build.make CMakeFiles/SystemAirport.dir/src/plane.c.s
.PHONY : src/plane.c.s

src/tower.o: src/tower.c.o

.PHONY : src/tower.o

# target to build an object file
src/tower.c.o:
	$(MAKE) -f CMakeFiles/SystemAirport.dir/build.make CMakeFiles/SystemAirport.dir/src/tower.c.o
.PHONY : src/tower.c.o

src/tower.i: src/tower.c.i

.PHONY : src/tower.i

# target to preprocess a source file
src/tower.c.i:
	$(MAKE) -f CMakeFiles/SystemAirport.dir/build.make CMakeFiles/SystemAirport.dir/src/tower.c.i
.PHONY : src/tower.c.i

src/tower.s: src/tower.c.s

.PHONY : src/tower.s

# target to generate assembly for a file
src/tower.c.s:
	$(MAKE) -f CMakeFiles/SystemAirport.dir/build.make CMakeFiles/SystemAirport.dir/src/tower.c.s
.PHONY : src/tower.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... SystemAirport"
	@echo "... edit_cache"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/plane.o"
	@echo "... src/plane.i"
	@echo "... src/plane.s"
	@echo "... src/tower.o"
	@echo "... src/tower.i"
	@echo "... src/tower.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

